(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un1751');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-50.php':'images/transparentks-284-81.php'):'images/transparentks-142-125.php');
var a='data-src';var e=document.querySelector('.un1752');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-43.php':'images/k-stransparent-424-87.php');
var e=document.querySelector('.un1748');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-48.php':'images/transparentks-284-80.php'):'images/transparentks-142-123.php');
var e=document.querySelector('.un1749');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-43.php':'images/k-stransparent-424-87.php');
var e=document.querySelector('.un1750');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-24.php':'images/csi-logo-272-41.php'):'images/csi-logo-136-83.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un1751');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-50.php':'images/transparentks-178-89.php'):'images/transparentks-89-89.php');
var a='data-src';var e=document.querySelector('.un1752');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-43.php':'images/k-stransparent-265-43.php');
var e=document.querySelector('.un1748');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-48.php':'images/transparentks-178-88.php'):'images/transparentks-89-88.php');
var e=document.querySelector('.un1749');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-43.php':'images/k-stransparent-265-43.php');
var e=document.querySelector('.un1750');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-24.php':'images/csi-logo-170-41.php'):'images/csi-logo-85-41.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un1751');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-24.php':'images/transparentks-142-124.php'):'images/transparentks-71-43.php');
var a='data-src';var e=document.querySelector('.un1752');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-24.php':'images/k-stransparent-424-86.php'):'images/k-stransparent-212-43.php');
var e=document.querySelector('.un1748');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-24.php':'images/transparentks-138-37.php'):'images/transparentks-69-37.php');
var e=document.querySelector('.un1749');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-24.php':'images/k-stransparent-424-86.php'):'images/k-stransparent-212-43.php');
var e=document.querySelector('.un1750');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-24.php':'images/csi-logo-136-82.php'):'images/csi-logo-68-41.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un1751');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-24.php':'images/transparentks-114-47.php'):'images/transparentks-57-47.php');
var a='data-src';var e=document.querySelector('.un1752');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-24.php':'images/k-stransparent-340-41.php'):'images/k-stransparent-170-41.php');
var e=document.querySelector('.un1748');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-24.php':'images/transparentks-110-37.php'):'images/transparentks-55-37.php');
var e=document.querySelector('.un1749');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-24.php':'images/k-stransparent-340-41.php'):'images/k-stransparent-170-41.php');
var e=document.querySelector('.un1750');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-24.php':'images/csi-logo-108-41.php'):'images/csi-logo-54-41.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un1751');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-24.php':'images/transparentks-306-43.php'):'images/transparentks-153-43.php');
var a='data-src';var e=document.querySelector('.un1752');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-24.php':'images/k-stransparent-330-43.php'):'images/k-stransparent-165-43.php');
var e=document.querySelector('.un1748');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-24.php':'images/transparentks-192-43.php'):'images/transparentks-96-43.php');
var e=document.querySelector('.un1749');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-24.php':'images/k-stransparent-392-35.php'):'images/k-stransparent-196-35.php');
var e=document.querySelector('.un1750');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-24.php':'images/csi-logo-174-35.php'):'images/csi-logo-87-35.php');}else{var a='data-src';var e=document.querySelector('.un1751');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-73.php':'images/transparentks-204-43.php'):'images/transparentks-102-43.php');
var a='data-src';var e=document.querySelector('.un1752');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-73.php':'images/k-stransparent-220-43.php'):'images/k-stransparent-110-43.php');
var e=document.querySelector('.un1748');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-73.php':'images/transparentks-128-43.php'):'images/transparentks-64-43.php');
var e=document.querySelector('.un1749');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-24.php':'images/k-stransparent-262-35.php'):'images/k-stransparent-131-35.php');
var e=document.querySelector('.un1750');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-65.php':'images/csi-logo-116-35.php'):'images/csi-logo-58-35.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un1753=new Plyr('.un1753 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1753.volume=0.8;
un1753.on('enterfullscreen',function(){pop.hide('popup195');});un1753.on('exitfullscreen',function(){pop.show('popup195');});pop.addHook('popup195',null,function(){un1753.stop()});un1754=new Plyr('.un1754 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1754.volume=0.8;
un1754.on('enterfullscreen',function(){pop.hide('popup194');});un1754.on('exitfullscreen',function(){pop.show('popup194');});pop.addHook('popup194',null,function(){un1754.stop()});un1755=new Plyr('.un1755 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1755.volume=0.8;
un1755.on('enterfullscreen',function(){pop.hide('popup193');});un1755.on('exitfullscreen',function(){pop.show('popup193');});pop.addHook('popup193',null,function(){un1755.stop()});un1756=new Plyr('.un1756 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1756.volume=0.8;
un1756.on('enterfullscreen',function(){pop.hide('popup192');});un1756.on('exitfullscreen',function(){pop.show('popup192');});pop.addHook('popup192',null,function(){un1756.stop()});un1757=new Plyr('.un1757 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1757.volume=0.8;
un1757.on('enterfullscreen',function(){pop.hide('popup191');});un1757.on('exitfullscreen',function(){pop.show('popup191');});pop.addHook('popup191',null,function(){un1757.stop()});un1758=new Plyr('.un1758 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1758.volume=0.8;
un1758.on('enterfullscreen',function(){pop.hide('popup189');});un1758.on('exitfullscreen',function(){pop.show('popup189');});pop.addHook('popup189',null,function(){un1758.stop()});un1759=new Plyr('.un1759 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1759.volume=0.8;
un1759.on('enterfullscreen',function(){pop.hide('popup188');});un1759.on('exitfullscreen',function(){pop.show('popup188');});pop.addHook('popup188',null,function(){un1759.stop()});un1760=new Plyr('.un1760 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1760.volume=0.8;
un1760.on('enterfullscreen',function(){pop.hide('popup187');});un1760.on('exitfullscreen',function(){pop.show('popup187');});pop.addHook('popup187',null,function(){un1760.stop()});un1761=new Plyr('.un1761 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1761.volume=0.8;
un1761.on('enterfullscreen',function(){pop.hide('popup190');});un1761.on('exitfullscreen',function(){pop.show('popup190');});pop.addHook('popup190',null,function(){un1761.stop()});un1762=new Plyr('.un1762 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1762.volume=0.8;
un1762.on('enterfullscreen',function(){pop.hide('popup196');});un1762.on('exitfullscreen',function(){pop.show('popup196');});pop.addHook('popup196',null,function(){un1762.stop()});un1763=new Plyr('.un1763 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1763.volume=0.8;
un1763.on('enterfullscreen',function(){pop.hide('popup186');});un1763.on('exitfullscreen',function(){pop.show('popup186');});pop.addHook('popup186',null,function(){un1763.stop()});un1764=new Plyr('.un1764 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1764.volume=0.8;
un1764.on('enterfullscreen',function(){pop.hide('popup185');});un1764.on('exitfullscreen',function(){pop.show('popup185');});pop.addHook('popup185',null,function(){un1764.stop()});un1765=new Plyr('.un1765 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1765.volume=0.8;
un1765.on('enterfullscreen',function(){pop.hide('popup184');});un1765.on('exitfullscreen',function(){pop.show('popup184');});pop.addHook('popup184',null,function(){un1765.stop()});un1766=new Plyr('.un1766 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1766.volume=0.8;
un1766.on('enterfullscreen',function(){pop.hide('popup183');});un1766.on('exitfullscreen',function(){pop.show('popup183');});pop.addHook('popup183',null,function(){un1766.stop()});un1767=new Plyr('.un1767 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1767.volume=0.8;
un1767.on('enterfullscreen',function(){pop.hide('popup182');});un1767.on('exitfullscreen',function(){pop.show('popup182');});pop.addHook('popup182',null,function(){un1767.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un1868 source');ldsrcset('.un1869 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}