(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un875');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-26.php':'images/transparentks-284-73.php'):'images/transparentks-142-113.php');
var a='data-src';var e=document.querySelector('.un876');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-39.php':'images/k-stransparent-424-79.php');
var e=document.querySelector('.un872');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-24.php':'images/transparentks-284-72.php'):'images/transparentks-142-111.php');
var e=document.querySelector('.un873');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-39.php':'images/k-stransparent-424-79.php');
var e=document.querySelector('.un874');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-12.php':'images/csi-logo-272-37.php'):'images/csi-logo-136-75.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un875');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-26.php':'images/transparentks-178-81.php'):'images/transparentks-89-81.php');
var a='data-src';var e=document.querySelector('.un876');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-39.php':'images/k-stransparent-265-39.php');
var e=document.querySelector('.un872');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-24.php':'images/transparentks-178-80.php'):'images/transparentks-89-80.php');
var e=document.querySelector('.un873');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-39.php':'images/k-stransparent-265-39.php');
var e=document.querySelector('.un874');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-12.php':'images/csi-logo-170-37.php'):'images/csi-logo-85-37.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un875');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-12.php':'images/transparentks-142-112.php'):'images/transparentks-71-39.php');
var a='data-src';var e=document.querySelector('.un876');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-12.php':'images/k-stransparent-424-78.php'):'images/k-stransparent-212-39.php');
var e=document.querySelector('.un872');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-12.php':'images/transparentks-138-33.php'):'images/transparentks-69-33.php');
var e=document.querySelector('.un873');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-12.php':'images/k-stransparent-424-78.php'):'images/k-stransparent-212-39.php');
var e=document.querySelector('.un874');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-12.php':'images/csi-logo-136-74.php'):'images/csi-logo-68-37.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un875');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-12.php':'images/transparentks-114-43.php'):'images/transparentks-57-43.php');
var a='data-src';var e=document.querySelector('.un876');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-12.php':'images/k-stransparent-340-37.php'):'images/k-stransparent-170-37.php');
var e=document.querySelector('.un872');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-12.php':'images/transparentks-110-33.php'):'images/transparentks-55-33.php');
var e=document.querySelector('.un873');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-12.php':'images/k-stransparent-340-37.php'):'images/k-stransparent-170-37.php');
var e=document.querySelector('.un874');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-12.php':'images/csi-logo-108-37.php'):'images/csi-logo-54-37.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un875');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-12.php':'images/transparentks-306-39.php'):'images/transparentks-153-39.php');
var a='data-src';var e=document.querySelector('.un876');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-12.php':'images/k-stransparent-330-39.php'):'images/k-stransparent-165-39.php');
var e=document.querySelector('.un872');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-12.php':'images/transparentks-192-39.php'):'images/transparentks-96-39.php');
var e=document.querySelector('.un873');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-12.php':'images/k-stransparent-392-31.php'):'images/k-stransparent-196-31.php');
var e=document.querySelector('.un874');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-12.php':'images/csi-logo-174-31.php'):'images/csi-logo-87-31.php');}else{var a='data-src';var e=document.querySelector('.un875');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-57.php':'images/transparentks-204-39.php'):'images/transparentks-102-39.php');
var a='data-src';var e=document.querySelector('.un876');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-57.php':'images/k-stransparent-220-39.php'):'images/k-stransparent-110-39.php');
var e=document.querySelector('.un872');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-57.php':'images/transparentks-128-39.php'):'images/transparentks-64-39.php');
var e=document.querySelector('.un873');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-12.php':'images/k-stransparent-262-31.php'):'images/k-stransparent-131-31.php');
var e=document.querySelector('.un874');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-49.php':'images/csi-logo-116-31.php'):'images/csi-logo-58-31.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un877=new Plyr('.un877 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un877.volume=0.8;
un877.on('enterfullscreen',function(){pop.hide('popup81');});un877.on('exitfullscreen',function(){pop.show('popup81');});pop.addHook('popup81',null,function(){un877.stop()});un878=new Plyr('.un878 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un878.volume=0.8;
un878.on('enterfullscreen',function(){pop.hide('popup80');});un878.on('exitfullscreen',function(){pop.show('popup80');});pop.addHook('popup80',null,function(){un878.stop()});un879=new Plyr('.un879 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un879.volume=0.8;
un879.on('enterfullscreen',function(){pop.hide('popup79');});un879.on('exitfullscreen',function(){pop.show('popup79');});pop.addHook('popup79',null,function(){un879.stop()});un880=new Plyr('.un880 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un880.volume=0.8;
un880.on('enterfullscreen',function(){pop.hide('popup78');});un880.on('exitfullscreen',function(){pop.show('popup78');});pop.addHook('popup78',null,function(){un880.stop()});un881=new Plyr('.un881 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un881.volume=0.8;
un881.on('enterfullscreen',function(){pop.hide('popup77');});un881.on('exitfullscreen',function(){pop.show('popup77');});pop.addHook('popup77',null,function(){un881.stop()});un882=new Plyr('.un882 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un882.volume=0.8;
un882.on('enterfullscreen',function(){pop.hide('popup76');});un882.on('exitfullscreen',function(){pop.show('popup76');});pop.addHook('popup76',null,function(){un882.stop()});un883=new Plyr('.un883 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un883.volume=0.8;
un883.on('enterfullscreen',function(){pop.hide('popup75');});un883.on('exitfullscreen',function(){pop.show('popup75');});pop.addHook('popup75',null,function(){un883.stop()});un884=new Plyr('.un884 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un884.volume=0.8;
un884.on('enterfullscreen',function(){pop.hide('popup74');});un884.on('exitfullscreen',function(){pop.show('popup74');});pop.addHook('popup74',null,function(){un884.stop()});un885=new Plyr('.un885 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un885.volume=0.8;
un885.on('enterfullscreen',function(){pop.hide('popup73');});un885.on('exitfullscreen',function(){pop.show('popup73');});pop.addHook('popup73',null,function(){un885.stop()});un886=new Plyr('.un886 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un886.volume=0.8;
un886.on('enterfullscreen',function(){pop.hide('popup82');});un886.on('exitfullscreen',function(){pop.show('popup82');});pop.addHook('popup82',null,function(){un886.stop()});un887=new Plyr('.un887 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un887.volume=0.8;
un887.on('enterfullscreen',function(){pop.hide('popup72');});un887.on('exitfullscreen',function(){pop.show('popup72');});pop.addHook('popup72',null,function(){un887.stop()});un888=new Plyr('.un888 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un888.volume=0.8;
un888.on('enterfullscreen',function(){pop.hide('popup71');});un888.on('exitfullscreen',function(){pop.show('popup71');});pop.addHook('popup71',null,function(){un888.stop()});un889=new Plyr('.un889 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un889.volume=0.8;
un889.on('enterfullscreen',function(){pop.hide('popup70');});un889.on('exitfullscreen',function(){pop.show('popup70');});pop.addHook('popup70',null,function(){un889.stop()});un890=new Plyr('.un890 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un890.volume=0.8;
un890.on('enterfullscreen',function(){pop.hide('popup69');});un890.on('exitfullscreen',function(){pop.show('popup69');});pop.addHook('popup69',null,function(){un890.stop()});un891=new Plyr('.un891 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un891.volume=0.8;
un891.on('enterfullscreen',function(){pop.hide('popup68');});un891.on('exitfullscreen',function(){pop.show('popup68');});pop.addHook('popup68',null,function(){un891.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un992 source');ldsrcset('.un993 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}