(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un1301');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-38.php':'images/transparentks-284-77.php'):'images/transparentks-142-119.php');
var a='data-src';var e=document.querySelector('.un1302');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-41.php':'images/k-stransparent-424-83.php');
var e=document.querySelector('.un1298');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-36.php':'images/transparentks-284-76.php'):'images/transparentks-142-117.php');
var e=document.querySelector('.un1299');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-41.php':'images/k-stransparent-424-83.php');
var e=document.querySelector('.un1300');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-18.php':'images/csi-logo-272-39.php'):'images/csi-logo-136-79.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un1301');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-38.php':'images/transparentks-178-85.php'):'images/transparentks-89-85.php');
var a='data-src';var e=document.querySelector('.un1302');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-41.php':'images/k-stransparent-265-41.php');
var e=document.querySelector('.un1298');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-36.php':'images/transparentks-178-84.php'):'images/transparentks-89-84.php');
var e=document.querySelector('.un1299');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-41.php':'images/k-stransparent-265-41.php');
var e=document.querySelector('.un1300');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-18.php':'images/csi-logo-170-39.php'):'images/csi-logo-85-39.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un1301');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-18.php':'images/transparentks-142-118.php'):'images/transparentks-71-41.php');
var a='data-src';var e=document.querySelector('.un1302');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-18.php':'images/k-stransparent-424-82.php'):'images/k-stransparent-212-41.php');
var e=document.querySelector('.un1298');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-18.php':'images/transparentks-138-35.php'):'images/transparentks-69-35.php');
var e=document.querySelector('.un1299');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-18.php':'images/k-stransparent-424-82.php'):'images/k-stransparent-212-41.php');
var e=document.querySelector('.un1300');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-18.php':'images/csi-logo-136-78.php'):'images/csi-logo-68-39.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un1301');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-18.php':'images/transparentks-114-45.php'):'images/transparentks-57-45.php');
var a='data-src';var e=document.querySelector('.un1302');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-18.php':'images/k-stransparent-340-39.php'):'images/k-stransparent-170-39.php');
var e=document.querySelector('.un1298');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-18.php':'images/transparentks-110-35.php'):'images/transparentks-55-35.php');
var e=document.querySelector('.un1299');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-18.php':'images/k-stransparent-340-39.php'):'images/k-stransparent-170-39.php');
var e=document.querySelector('.un1300');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-18.php':'images/csi-logo-108-39.php'):'images/csi-logo-54-39.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un1301');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-18.php':'images/transparentks-306-41.php'):'images/transparentks-153-41.php');
var a='data-src';var e=document.querySelector('.un1302');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-18.php':'images/k-stransparent-330-41.php'):'images/k-stransparent-165-41.php');
var e=document.querySelector('.un1298');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-18.php':'images/transparentks-192-41.php'):'images/transparentks-96-41.php');
var e=document.querySelector('.un1299');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-18.php':'images/k-stransparent-392-33.php'):'images/k-stransparent-196-33.php');
var e=document.querySelector('.un1300');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-18.php':'images/csi-logo-174-33.php'):'images/csi-logo-87-33.php');}else{var a='data-src';var e=document.querySelector('.un1301');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-65.php':'images/transparentks-204-41.php'):'images/transparentks-102-41.php');
var a='data-src';var e=document.querySelector('.un1302');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-65.php':'images/k-stransparent-220-41.php'):'images/k-stransparent-110-41.php');
var e=document.querySelector('.un1298');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-65.php':'images/transparentks-128-41.php'):'images/transparentks-64-41.php');
var e=document.querySelector('.un1299');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-18.php':'images/k-stransparent-262-33.php'):'images/k-stransparent-131-33.php');
var e=document.querySelector('.un1300');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-57.php':'images/csi-logo-116-33.php'):'images/csi-logo-58-33.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un1303=new Plyr('.un1303 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1303.volume=0.8;
un1303.on('enterfullscreen',function(){pop.hide('popup145');});un1303.on('exitfullscreen',function(){pop.show('popup145');});pop.addHook('popup145',null,function(){un1303.stop()});un1304=new Plyr('.un1304 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1304.volume=0.8;
un1304.on('enterfullscreen',function(){pop.hide('popup144');});un1304.on('exitfullscreen',function(){pop.show('popup144');});pop.addHook('popup144',null,function(){un1304.stop()});un1305=new Plyr('.un1305 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1305.volume=0.8;
un1305.on('enterfullscreen',function(){pop.hide('popup143');});un1305.on('exitfullscreen',function(){pop.show('popup143');});pop.addHook('popup143',null,function(){un1305.stop()});un1306=new Plyr('.un1306 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1306.volume=0.8;
un1306.on('enterfullscreen',function(){pop.hide('popup142');});un1306.on('exitfullscreen',function(){pop.show('popup142');});pop.addHook('popup142',null,function(){un1306.stop()});un1307=new Plyr('.un1307 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1307.volume=0.8;
un1307.on('enterfullscreen',function(){pop.hide('popup141');});un1307.on('exitfullscreen',function(){pop.show('popup141');});pop.addHook('popup141',null,function(){un1307.stop()});un1308=new Plyr('.un1308 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1308.volume=0.8;
un1308.on('enterfullscreen',function(){pop.hide('popup140');});un1308.on('exitfullscreen',function(){pop.show('popup140');});pop.addHook('popup140',null,function(){un1308.stop()});un1309=new Plyr('.un1309 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1309.volume=0.8;
un1309.on('enterfullscreen',function(){pop.hide('popup139');});un1309.on('exitfullscreen',function(){pop.show('popup139');});pop.addHook('popup139',null,function(){un1309.stop()});un1310=new Plyr('.un1310 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1310.volume=0.8;
un1310.on('enterfullscreen',function(){pop.hide('popup138');});un1310.on('exitfullscreen',function(){pop.show('popup138');});pop.addHook('popup138',null,function(){un1310.stop()});un1311=new Plyr('.un1311 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1311.volume=0.8;
un1311.on('enterfullscreen',function(){pop.hide('popup137');});un1311.on('exitfullscreen',function(){pop.show('popup137');});pop.addHook('popup137',null,function(){un1311.stop()});un1312=new Plyr('.un1312 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1312.volume=0.8;
un1312.on('enterfullscreen',function(){pop.hide('popup136');});un1312.on('exitfullscreen',function(){pop.show('popup136');});pop.addHook('popup136',null,function(){un1312.stop()});un1313=new Plyr('.un1313 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1313.volume=0.8;
un1313.on('enterfullscreen',function(){pop.hide('popup135');});un1313.on('exitfullscreen',function(){pop.show('popup135');});pop.addHook('popup135',null,function(){un1313.stop()});un1314=new Plyr('.un1314 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1314.volume=0.8;
un1314.on('enterfullscreen',function(){pop.hide('popup134');});un1314.on('exitfullscreen',function(){pop.show('popup134');});pop.addHook('popup134',null,function(){un1314.stop()});un1315=new Plyr('.un1315 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1315.volume=0.8;
un1315.on('enterfullscreen',function(){pop.hide('popup146');});un1315.on('exitfullscreen',function(){pop.show('popup146');});pop.addHook('popup146',null,function(){un1315.stop()});un1316=new Plyr('.un1316 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1316.volume=0.8;
un1316.on('enterfullscreen',function(){pop.hide('popup133');});un1316.on('exitfullscreen',function(){pop.show('popup133');});pop.addHook('popup133',null,function(){un1316.stop()});un1317=new Plyr('.un1317 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1317.volume=0.8;
un1317.on('enterfullscreen',function(){pop.hide('popup132');});un1317.on('exitfullscreen',function(){pop.show('popup132');});pop.addHook('popup132',null,function(){un1317.stop()});un1318=new Plyr('.un1318 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1318.volume=0.8;
un1318.on('enterfullscreen',function(){pop.hide('popup131');});un1318.on('exitfullscreen',function(){pop.show('popup131');});pop.addHook('popup131',null,function(){un1318.stop()});un1319=new Plyr('.un1319 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1319.volume=0.8;
un1319.on('enterfullscreen',function(){pop.hide('popup130');});un1319.on('exitfullscreen',function(){pop.show('popup130');});pop.addHook('popup130',null,function(){un1319.stop()});un1320=new Plyr('.un1320 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1320.volume=0.8;
un1320.on('enterfullscreen',function(){pop.hide('popup129');});un1320.on('exitfullscreen',function(){pop.show('popup129');});pop.addHook('popup129',null,function(){un1320.stop()});un1321=new Plyr('.un1321 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1321.volume=0.8;
un1321.on('enterfullscreen',function(){pop.hide('popup128');});un1321.on('exitfullscreen',function(){pop.show('popup128');});pop.addHook('popup128',null,function(){un1321.stop()});un1322=new Plyr('.un1322 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1322.volume=0.8;
un1322.on('enterfullscreen',function(){pop.hide('popup127');});un1322.on('exitfullscreen',function(){pop.show('popup127');});pop.addHook('popup127',null,function(){un1322.stop()});un1323=new Plyr('.un1323 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1323.volume=0.8;
un1323.on('enterfullscreen',function(){pop.hide('popup126');});un1323.on('exitfullscreen',function(){pop.show('popup126');});pop.addHook('popup126',null,function(){un1323.stop()});un1324=new Plyr('.un1324 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1324.volume=0.8;
un1324.on('enterfullscreen',function(){pop.hide('popup125');});un1324.on('exitfullscreen',function(){pop.show('popup125');});pop.addHook('popup125',null,function(){un1324.stop()});un1325=new Plyr('.un1325 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1325.volume=0.8;
un1325.on('enterfullscreen',function(){pop.hide('popup124');});un1325.on('exitfullscreen',function(){pop.show('popup124');});pop.addHook('popup124',null,function(){un1325.stop()});un1326=new Plyr('.un1326 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1326.volume=0.8;
un1326.on('enterfullscreen',function(){pop.hide('popup123');});un1326.on('exitfullscreen',function(){pop.show('popup123');});pop.addHook('popup123',null,function(){un1326.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un1472 source');ldsrcset('.un1473 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}