(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un1629');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-46.php':'images/transparentks-284-68.php'):'images/transparentks-142-106.php');
var a='data-src';var e=document.querySelector('.un1630');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-36.php':'images/k-stransparent-424-74.php');
var e=document.querySelector('.un1626');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-44.php':'images/transparentks-284-66.php'):'images/transparentks-142-102.php');
var e=document.querySelector('.un1627');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-36.php':'images/k-stransparent-424-74.php');
var e=document.querySelector('.un1628');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-22.php':'images/csi-logo-272-34.php'):'images/csi-logo-136-70.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un1629');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-46.php':'images/transparentks-178-76.php'):'images/transparentks-89-76.php');
var a='data-src';var e=document.querySelector('.un1630');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-36.php':'images/k-stransparent-265-36.php');
var e=document.querySelector('.un1626');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-44.php':'images/transparentks-178-74.php'):'images/transparentks-89-74.php');
var e=document.querySelector('.un1627');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-36.php':'images/k-stransparent-265-36.php');
var e=document.querySelector('.un1628');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-22.php':'images/csi-logo-170-34.php'):'images/csi-logo-85-34.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un1629');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-22.php':'images/transparentks-142-104.php'):'images/transparentks-71-36.php');
var a='data-src';var e=document.querySelector('.un1630');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-22.php':'images/k-stransparent-424-72.php'):'images/k-stransparent-212-36.php');
var e=document.querySelector('.un1626');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-22.php':'images/transparentks-138-30.php'):'images/transparentks-69-30.php');
var e=document.querySelector('.un1627');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-22.php':'images/k-stransparent-424-72.php'):'images/k-stransparent-212-36.php');
var e=document.querySelector('.un1628');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-22.php':'images/csi-logo-136-68.php'):'images/csi-logo-68-34.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un1629');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-22.php':'images/transparentks-114-40.php'):'images/transparentks-57-40.php');
var a='data-src';var e=document.querySelector('.un1630');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-22.php':'images/k-stransparent-340-34.php'):'images/k-stransparent-170-34.php');
var e=document.querySelector('.un1626');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-22.php':'images/transparentks-110-30.php'):'images/transparentks-55-30.php');
var e=document.querySelector('.un1627');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-22.php':'images/k-stransparent-340-34.php'):'images/k-stransparent-170-34.php');
var e=document.querySelector('.un1628');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-22.php':'images/csi-logo-108-34.php'):'images/csi-logo-54-34.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un1629');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-22.php':'images/transparentks-306-36.php'):'images/transparentks-153-36.php');
var a='data-src';var e=document.querySelector('.un1630');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-22.php':'images/k-stransparent-330-36.php'):'images/k-stransparent-165-36.php');
var e=document.querySelector('.un1626');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-22.php':'images/transparentks-192-36.php'):'images/transparentks-96-36.php');
var e=document.querySelector('.un1627');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-22.php':'images/k-stransparent-392-28.php'):'images/k-stransparent-196-28.php');
var e=document.querySelector('.un1628');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-22.php':'images/csi-logo-174-28.php'):'images/csi-logo-87-28.php');}else{var a='data-src';var e=document.querySelector('.un1629');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-71.php':'images/transparentks-204-36.php'):'images/transparentks-102-36.php');
var a='data-src';var e=document.querySelector('.un1630');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-71.php':'images/k-stransparent-220-36.php'):'images/k-stransparent-110-36.php');
var e=document.querySelector('.un1626');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-71.php':'images/transparentks-128-36.php'):'images/transparentks-64-36.php');
var e=document.querySelector('.un1627');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-22.php':'images/k-stransparent-262-28.php'):'images/k-stransparent-131-28.php');
var e=document.querySelector('.un1628');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-63.php':'images/csi-logo-116-28.php'):'images/csi-logo-58-28.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un1631=new Plyr('.un1631 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1631.volume=0.8;
un1631.on('enterfullscreen',function(){pop.hide('popup181');});un1631.on('exitfullscreen',function(){pop.show('popup181');});pop.addHook('popup181',null,function(){un1631.stop()});un1632=new Plyr('.un1632 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1632.volume=0.8;
un1632.on('enterfullscreen',function(){pop.hide('popup180');});un1632.on('exitfullscreen',function(){pop.show('popup180');});pop.addHook('popup180',null,function(){un1632.stop()});un1633=new Plyr('.un1633 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1633.volume=0.8;
un1633.on('enterfullscreen',function(){pop.hide('popup179');});un1633.on('exitfullscreen',function(){pop.show('popup179');});pop.addHook('popup179',null,function(){un1633.stop()});un1634=new Plyr('.un1634 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1634.volume=0.8;
un1634.on('enterfullscreen',function(){pop.hide('popup178');});un1634.on('exitfullscreen',function(){pop.show('popup178');});pop.addHook('popup178',null,function(){un1634.stop()});un1635=new Plyr('.un1635 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1635.volume=0.8;
un1635.on('enterfullscreen',function(){pop.hide('popup177');});un1635.on('exitfullscreen',function(){pop.show('popup177');});pop.addHook('popup177',null,function(){un1635.stop()});un1636=new Plyr('.un1636 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1636.volume=0.8;
un1636.on('enterfullscreen',function(){pop.hide('popup176');});un1636.on('exitfullscreen',function(){pop.show('popup176');});pop.addHook('popup176',null,function(){un1636.stop()});un1637=new Plyr('.un1637 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1637.volume=0.8;
un1637.on('enterfullscreen',function(){pop.hide('popup174');});un1637.on('exitfullscreen',function(){pop.show('popup174');});pop.addHook('popup174',null,function(){un1637.stop()});un1638=new Plyr('.un1638 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1638.volume=0.8;
un1638.on('enterfullscreen',function(){pop.hide('popup173');});un1638.on('exitfullscreen',function(){pop.show('popup173');});pop.addHook('popup173',null,function(){un1638.stop()});un1639=new Plyr('.un1639 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1639.volume=0.8;
un1639.on('enterfullscreen',function(){pop.hide('popup175');});un1639.on('exitfullscreen',function(){pop.show('popup175');});pop.addHook('popup175',null,function(){un1639.stop()});un1640=new Plyr('.un1640 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1640.volume=0.8;
un1640.on('enterfullscreen',function(){pop.hide('popup172');});un1640.on('exitfullscreen',function(){pop.show('popup172');});pop.addHook('popup172',null,function(){un1640.stop()});un1641=new Plyr('.un1641 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1641.volume=0.8;
un1641.on('enterfullscreen',function(){pop.hide('popup171');});un1641.on('exitfullscreen',function(){pop.show('popup171');});pop.addHook('popup171',null,function(){un1641.stop()});un1642=new Plyr('.un1642 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1642.volume=0.8;
un1642.on('enterfullscreen',function(){pop.hide('popup170');});un1642.on('exitfullscreen',function(){pop.show('popup170');});pop.addHook('popup170',null,function(){un1642.stop()});un1643=new Plyr('.un1643 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1643.volume=0.8;
un1643.on('enterfullscreen',function(){pop.hide('popup169');});un1643.on('exitfullscreen',function(){pop.show('popup169');});pop.addHook('popup169',null,function(){un1643.stop()});un1644=new Plyr('.un1644 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1644.volume=0.8;
un1644.on('enterfullscreen',function(){pop.hide('popup168');});un1644.on('exitfullscreen',function(){pop.show('popup168');});pop.addHook('popup168',null,function(){un1644.stop()});un1645=new Plyr('.un1645 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1645.volume=0.8;
un1645.on('enterfullscreen',function(){pop.hide('popup167');});un1645.on('exitfullscreen',function(){pop.show('popup167');});pop.addHook('popup167',null,function(){un1645.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un1746 source');ldsrcset('.un1747 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}