(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un997');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-30.php':'images/transparentks-284-64.php'):'images/transparentks-142-100.php');
var a='data-src';var e=document.querySelector('.un998');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-34.php':'images/k-stransparent-424-70.php');
var e=document.querySelector('.un994');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-28.php':'images/transparentks-284-62.php'):'images/transparentks-142-96.php');
var e=document.querySelector('.un995');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-34.php':'images/k-stransparent-424-70.php');
var e=document.querySelector('.un996');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-14.php':'images/csi-logo-272-32.php'):'images/csi-logo-136-66.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un997');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-30.php':'images/transparentks-178-72.php'):'images/transparentks-89-72.php');
var a='data-src';var e=document.querySelector('.un998');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-34.php':'images/k-stransparent-265-34.php');
var e=document.querySelector('.un994');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-28.php':'images/transparentks-178-70.php'):'images/transparentks-89-70.php');
var e=document.querySelector('.un995');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-34.php':'images/k-stransparent-265-34.php');
var e=document.querySelector('.un996');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-14.php':'images/csi-logo-170-32.php'):'images/csi-logo-85-32.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un997');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-14.php':'images/transparentks-142-98.php'):'images/transparentks-71-34.php');
var a='data-src';var e=document.querySelector('.un998');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-14.php':'images/k-stransparent-424-68.php'):'images/k-stransparent-212-34.php');
var e=document.querySelector('.un994');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-14.php':'images/transparentks-138-28.php'):'images/transparentks-69-28.php');
var e=document.querySelector('.un995');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-14.php':'images/k-stransparent-424-68.php'):'images/k-stransparent-212-34.php');
var e=document.querySelector('.un996');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-14.php':'images/csi-logo-136-64.php'):'images/csi-logo-68-32.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un997');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-14.php':'images/transparentks-114-38.php'):'images/transparentks-57-38.php');
var a='data-src';var e=document.querySelector('.un998');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-14.php':'images/k-stransparent-340-32.php'):'images/k-stransparent-170-32.php');
var e=document.querySelector('.un994');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-14.php':'images/transparentks-110-28.php'):'images/transparentks-55-28.php');
var e=document.querySelector('.un995');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-14.php':'images/k-stransparent-340-32.php'):'images/k-stransparent-170-32.php');
var e=document.querySelector('.un996');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-14.php':'images/csi-logo-108-32.php'):'images/csi-logo-54-32.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un997');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-14.php':'images/transparentks-306-34.php'):'images/transparentks-153-34.php');
var a='data-src';var e=document.querySelector('.un998');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-14.php':'images/k-stransparent-330-34.php'):'images/k-stransparent-165-34.php');
var e=document.querySelector('.un994');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-14.php':'images/transparentks-192-34.php'):'images/transparentks-96-34.php');
var e=document.querySelector('.un995');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-14.php':'images/k-stransparent-392-26.php'):'images/k-stransparent-196-26.php');
var e=document.querySelector('.un996');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-14.php':'images/csi-logo-174-26.php'):'images/csi-logo-87-26.php');}else{var a='data-src';var e=document.querySelector('.un997');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-60.php':'images/transparentks-204-34.php'):'images/transparentks-102-34.php');
var a='data-src';var e=document.querySelector('.un998');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-60.php':'images/k-stransparent-220-34.php'):'images/k-stransparent-110-34.php');
var e=document.querySelector('.un994');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-60.php':'images/transparentks-128-34.php'):'images/transparentks-64-34.php');
var e=document.querySelector('.un995');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-14.php':'images/k-stransparent-262-26.php'):'images/k-stransparent-131-26.php');
var e=document.querySelector('.un996');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-52.php':'images/csi-logo-116-26.php'):'images/csi-logo-58-26.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un999=new Plyr('.un999 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un999.volume=0.8;
un999.on('enterfullscreen',function(){pop.hide('popup101');});un999.on('exitfullscreen',function(){pop.show('popup101');});pop.addHook('popup101',null,function(){un999.stop()});un1000=new Plyr('.un1000 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1000.volume=0.8;
un1000.on('enterfullscreen',function(){pop.hide('popup100');});un1000.on('exitfullscreen',function(){pop.show('popup100');});pop.addHook('popup100',null,function(){un1000.stop()});un1001=new Plyr('.un1001 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1001.volume=0.8;
un1001.on('enterfullscreen',function(){pop.hide('popup99');});un1001.on('exitfullscreen',function(){pop.show('popup99');});pop.addHook('popup99',null,function(){un1001.stop()});un1002=new Plyr('.un1002 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1002.volume=0.8;
un1002.on('enterfullscreen',function(){pop.hide('popup98');});un1002.on('exitfullscreen',function(){pop.show('popup98');});pop.addHook('popup98',null,function(){un1002.stop()});un1003=new Plyr('.un1003 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1003.volume=0.8;
un1003.on('enterfullscreen',function(){pop.hide('popup97');});un1003.on('exitfullscreen',function(){pop.show('popup97');});pop.addHook('popup97',null,function(){un1003.stop()});un1004=new Plyr('.un1004 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1004.volume=0.8;
un1004.on('enterfullscreen',function(){pop.hide('popup96');});un1004.on('exitfullscreen',function(){pop.show('popup96');});pop.addHook('popup96',null,function(){un1004.stop()});un1005=new Plyr('.un1005 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1005.volume=0.8;
un1005.on('enterfullscreen',function(){pop.hide('popup102');});un1005.on('exitfullscreen',function(){pop.show('popup102');});pop.addHook('popup102',null,function(){un1005.stop()});un1006=new Plyr('.un1006 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1006.volume=0.8;
un1006.on('enterfullscreen',function(){pop.hide('popup95');});un1006.on('exitfullscreen',function(){pop.show('popup95');});pop.addHook('popup95',null,function(){un1006.stop()});un1007=new Plyr('.un1007 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1007.volume=0.8;
un1007.on('enterfullscreen',function(){pop.hide('popup94');});un1007.on('exitfullscreen',function(){pop.show('popup94');});pop.addHook('popup94',null,function(){un1007.stop()});un1008=new Plyr('.un1008 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1008.volume=0.8;
un1008.on('enterfullscreen',function(){pop.hide('popup93');});un1008.on('exitfullscreen',function(){pop.show('popup93');});pop.addHook('popup93',null,function(){un1008.stop()});un1009=new Plyr('.un1009 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1009.volume=0.8;
un1009.on('enterfullscreen',function(){pop.hide('popup92');});un1009.on('exitfullscreen',function(){pop.show('popup92');});pop.addHook('popup92',null,function(){un1009.stop()});un1010=new Plyr('.un1010 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1010.volume=0.8;
un1010.on('enterfullscreen',function(){pop.hide('popup91');});un1010.on('exitfullscreen',function(){pop.show('popup91');});pop.addHook('popup91',null,function(){un1010.stop()});un1011=new Plyr('.un1011 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1011.volume=0.8;
un1011.on('enterfullscreen',function(){pop.hide('popup90');});un1011.on('exitfullscreen',function(){pop.show('popup90');});pop.addHook('popup90',null,function(){un1011.stop()});un1012=new Plyr('.un1012 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1012.volume=0.8;
un1012.on('enterfullscreen',function(){pop.hide('popup89');});un1012.on('exitfullscreen',function(){pop.show('popup89');});pop.addHook('popup89',null,function(){un1012.stop()});un1013=new Plyr('.un1013 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1013.volume=0.8;
un1013.on('enterfullscreen',function(){pop.hide('popup88');});un1013.on('exitfullscreen',function(){pop.show('popup88');});pop.addHook('popup88',null,function(){un1013.stop()});un1014=new Plyr('.un1014 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1014.volume=0.8;
un1014.on('enterfullscreen',function(){pop.hide('popup87');});un1014.on('exitfullscreen',function(){pop.show('popup87');});pop.addHook('popup87',null,function(){un1014.stop()});un1015=new Plyr('.un1015 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1015.volume=0.8;
un1015.on('enterfullscreen',function(){pop.hide('popup86');});un1015.on('exitfullscreen',function(){pop.show('popup86');});pop.addHook('popup86',null,function(){un1015.stop()});un1016=new Plyr('.un1016 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1016.volume=0.8;
un1016.on('enterfullscreen',function(){pop.hide('popup85');});un1016.on('exitfullscreen',function(){pop.show('popup85');});pop.addHook('popup85',null,function(){un1016.stop()});un1017=new Plyr('.un1017 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1017.volume=0.8;
un1017.on('enterfullscreen',function(){pop.hide('popup84');});un1017.on('exitfullscreen',function(){pop.show('popup84');});pop.addHook('popup84',null,function(){un1017.stop()});un1018=new Plyr('.un1018 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1018.volume=0.8;
un1018.on('enterfullscreen',function(){pop.hide('popup83');});un1018.on('exitfullscreen',function(){pop.show('popup83');});pop.addHook('popup83',null,function(){un1018.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un1144 source');ldsrcset('.un1145 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}