(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un649');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-18.php':'images/transparentks-284-60.php'):'images/transparentks-142-94.php');
var a='data-src';var e=document.querySelector('.un650');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-32.php':'images/k-stransparent-424-66.php');
var e=document.querySelector('.un646');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-16.php':'images/transparentks-284-58.php'):'images/transparentks-142-90.php');
var e=document.querySelector('.un647');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-32.php':'images/k-stransparent-424-66.php');
var e=document.querySelector('.un648');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-8.php':'images/csi-logo-272-30.php'):'images/csi-logo-136-62.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un649');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-18.php':'images/transparentks-178-68.php'):'images/transparentks-89-68.php');
var a='data-src';var e=document.querySelector('.un650');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-32.php':'images/k-stransparent-265-32.php');
var e=document.querySelector('.un646');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-16.php':'images/transparentks-178-66.php'):'images/transparentks-89-66.php');
var e=document.querySelector('.un647');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-32.php':'images/k-stransparent-265-32.php');
var e=document.querySelector('.un648');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-8.php':'images/csi-logo-170-30.php'):'images/csi-logo-85-30.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un649');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-8.php':'images/transparentks-142-92.php'):'images/transparentks-71-32.php');
var a='data-src';var e=document.querySelector('.un650');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-8.php':'images/k-stransparent-424-64.php'):'images/k-stransparent-212-32.php');
var e=document.querySelector('.un646');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-8.php':'images/transparentks-138-26.php'):'images/transparentks-69-26.php');
var e=document.querySelector('.un647');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-8.php':'images/k-stransparent-424-64.php'):'images/k-stransparent-212-32.php');
var e=document.querySelector('.un648');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-8.php':'images/csi-logo-136-60.php'):'images/csi-logo-68-30.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un649');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-8.php':'images/transparentks-114-36.php'):'images/transparentks-57-36.php');
var a='data-src';var e=document.querySelector('.un650');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-8.php':'images/k-stransparent-340-30.php'):'images/k-stransparent-170-30.php');
var e=document.querySelector('.un646');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-8.php':'images/transparentks-110-26.php'):'images/transparentks-55-26.php');
var e=document.querySelector('.un647');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-8.php':'images/k-stransparent-340-30.php'):'images/k-stransparent-170-30.php');
var e=document.querySelector('.un648');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-8.php':'images/csi-logo-108-30.php'):'images/csi-logo-54-30.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un649');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-8.php':'images/transparentks-306-32.php'):'images/transparentks-153-32.php');
var a='data-src';var e=document.querySelector('.un650');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-8.php':'images/k-stransparent-330-32.php'):'images/k-stransparent-165-32.php');
var e=document.querySelector('.un646');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-8.php':'images/transparentks-192-32.php'):'images/transparentks-96-32.php');
var e=document.querySelector('.un647');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-8.php':'images/k-stransparent-392-24.php'):'images/k-stransparent-196-24.php');
var e=document.querySelector('.un648');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-8.php':'images/csi-logo-174-24.php'):'images/csi-logo-87-24.php');}else{var a='data-src';var e=document.querySelector('.un649');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-52.php':'images/transparentks-204-32.php'):'images/transparentks-102-32.php');
var a='data-src';var e=document.querySelector('.un650');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-52.php':'images/k-stransparent-220-32.php'):'images/k-stransparent-110-32.php');
var e=document.querySelector('.un646');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-52.php':'images/transparentks-128-32.php'):'images/transparentks-64-32.php');
var e=document.querySelector('.un647');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-8.php':'images/k-stransparent-262-24.php'):'images/k-stransparent-131-24.php');
var e=document.querySelector('.un648');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-44.php':'images/csi-logo-116-24.php'):'images/csi-logo-58-24.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un651=new Plyr('.un651 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un651.volume=0.8;
un651.on('enterfullscreen',function(){pop.hide('popup45');});un651.on('exitfullscreen',function(){pop.show('popup45');});pop.addHook('popup45',null,function(){un651.stop()});un652=new Plyr('.un652 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un652.volume=0.8;
un652.on('enterfullscreen',function(){pop.hide('popup44');});un652.on('exitfullscreen',function(){pop.show('popup44');});pop.addHook('popup44',null,function(){un652.stop()});un653=new Plyr('.un653 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un653.volume=0.8;
un653.on('enterfullscreen',function(){pop.hide('popup43');});un653.on('exitfullscreen',function(){pop.show('popup43');});pop.addHook('popup43',null,function(){un653.stop()});un654=new Plyr('.un654 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un654.volume=0.8;
un654.on('enterfullscreen',function(){pop.hide('popup55');});un654.on('exitfullscreen',function(){pop.show('popup55');});pop.addHook('popup55',null,function(){un654.stop()});un655=new Plyr('.un655 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un655.volume=0.8;
un655.on('enterfullscreen',function(){pop.hide('popup54');});un655.on('exitfullscreen',function(){pop.show('popup54');});pop.addHook('popup54',null,function(){un655.stop()});un656=new Plyr('.un656 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un656.volume=0.8;
un656.on('enterfullscreen',function(){pop.hide('popup53');});un656.on('exitfullscreen',function(){pop.show('popup53');});pop.addHook('popup53',null,function(){un656.stop()});un657=new Plyr('.un657 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un657.volume=0.8;
un657.on('enterfullscreen',function(){pop.hide('popup52');});un657.on('exitfullscreen',function(){pop.show('popup52');});pop.addHook('popup52',null,function(){un657.stop()});un658=new Plyr('.un658 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un658.volume=0.8;
un658.on('enterfullscreen',function(){pop.hide('popup51');});un658.on('exitfullscreen',function(){pop.show('popup51');});pop.addHook('popup51',null,function(){un658.stop()});un659=new Plyr('.un659 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un659.volume=0.8;
un659.on('enterfullscreen',function(){pop.hide('popup50');});un659.on('exitfullscreen',function(){pop.show('popup50');});pop.addHook('popup50',null,function(){un659.stop()});un660=new Plyr('.un660 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un660.volume=0.8;
un660.on('enterfullscreen',function(){pop.hide('popup49');});un660.on('exitfullscreen',function(){pop.show('popup49');});pop.addHook('popup49',null,function(){un660.stop()});un661=new Plyr('.un661 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un661.volume=0.8;
un661.on('enterfullscreen',function(){pop.hide('popup48');});un661.on('exitfullscreen',function(){pop.show('popup48');});pop.addHook('popup48',null,function(){un661.stop()});un662=new Plyr('.un662 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un662.volume=0.8;
un662.on('enterfullscreen',function(){pop.hide('popup47');});un662.on('exitfullscreen',function(){pop.show('popup47');});pop.addHook('popup47',null,function(){un662.stop()});un663=new Plyr('.un663 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un663.volume=0.8;
un663.on('enterfullscreen',function(){pop.hide('popup46');});un663.on('exitfullscreen',function(){pop.show('popup46');});pop.addHook('popup46',null,function(){un663.stop()});un664=new Plyr('.un664 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un664.volume=0.8;
un664.on('enterfullscreen',function(){pop.hide('popup42');});un664.on('exitfullscreen',function(){pop.show('popup42');});pop.addHook('popup42',null,function(){un664.stop()});un665=new Plyr('.un665 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un665.volume=0.8;
un665.on('enterfullscreen',function(){pop.hide('popup41');});un665.on('exitfullscreen',function(){pop.show('popup41');});pop.addHook('popup41',null,function(){un665.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un766 source');ldsrcset('.un767 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}