(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un1149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-34.php':'images/transparentks-284-75.php'):'images/transparentks-142-116.php');
var a='data-src';var e=document.querySelector('.un1150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-40.php':'images/k-stransparent-424-81.php');
var e=document.querySelector('.un1146');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-32.php':'images/transparentks-284-74.php'):'images/transparentks-142-114.php');
var e=document.querySelector('.un1147');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-40.php':'images/k-stransparent-424-81.php');
var e=document.querySelector('.un1148');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-16.php':'images/csi-logo-272-38.php'):'images/csi-logo-136-77.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un1149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-34.php':'images/transparentks-178-83.php'):'images/transparentks-89-83.php');
var a='data-src';var e=document.querySelector('.un1150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-40.php':'images/k-stransparent-265-40.php');
var e=document.querySelector('.un1146');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-32.php':'images/transparentks-178-82.php'):'images/transparentks-89-82.php');
var e=document.querySelector('.un1147');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-40.php':'images/k-stransparent-265-40.php');
var e=document.querySelector('.un1148');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-16.php':'images/csi-logo-170-38.php'):'images/csi-logo-85-38.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un1149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-16.php':'images/transparentks-142-115.php'):'images/transparentks-71-40.php');
var a='data-src';var e=document.querySelector('.un1150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-16.php':'images/k-stransparent-424-80.php'):'images/k-stransparent-212-40.php');
var e=document.querySelector('.un1146');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-16.php':'images/transparentks-138-34.php'):'images/transparentks-69-34.php');
var e=document.querySelector('.un1147');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-16.php':'images/k-stransparent-424-80.php'):'images/k-stransparent-212-40.php');
var e=document.querySelector('.un1148');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-16.php':'images/csi-logo-136-76.php'):'images/csi-logo-68-38.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un1149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-16.php':'images/transparentks-114-44.php'):'images/transparentks-57-44.php');
var a='data-src';var e=document.querySelector('.un1150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-16.php':'images/k-stransparent-340-38.php'):'images/k-stransparent-170-38.php');
var e=document.querySelector('.un1146');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-16.php':'images/transparentks-110-34.php'):'images/transparentks-55-34.php');
var e=document.querySelector('.un1147');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-16.php':'images/k-stransparent-340-38.php'):'images/k-stransparent-170-38.php');
var e=document.querySelector('.un1148');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-16.php':'images/csi-logo-108-38.php'):'images/csi-logo-54-38.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un1149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-16.php':'images/transparentks-306-40.php'):'images/transparentks-153-40.php');
var a='data-src';var e=document.querySelector('.un1150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-16.php':'images/k-stransparent-330-40.php'):'images/k-stransparent-165-40.php');
var e=document.querySelector('.un1146');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-16.php':'images/transparentks-192-40.php'):'images/transparentks-96-40.php');
var e=document.querySelector('.un1147');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-16.php':'images/k-stransparent-392-32.php'):'images/k-stransparent-196-32.php');
var e=document.querySelector('.un1148');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-16.php':'images/csi-logo-174-32.php'):'images/csi-logo-87-32.php');}else{var a='data-src';var e=document.querySelector('.un1149');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-62.php':'images/transparentks-204-40.php'):'images/transparentks-102-40.php');
var a='data-src';var e=document.querySelector('.un1150');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-62.php':'images/k-stransparent-220-40.php'):'images/k-stransparent-110-40.php');
var e=document.querySelector('.un1146');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-62.php':'images/transparentks-128-40.php'):'images/transparentks-64-40.php');
var e=document.querySelector('.un1147');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-16.php':'images/k-stransparent-262-32.php'):'images/k-stransparent-131-32.php');
var e=document.querySelector('.un1148');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-54.php':'images/csi-logo-116-32.php'):'images/csi-logo-58-32.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un1151=new Plyr('.un1151 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1151.volume=0.8;
un1151.on('enterfullscreen',function(){pop.hide('popup121');});un1151.on('exitfullscreen',function(){pop.show('popup121');});pop.addHook('popup121',null,function(){un1151.stop()});un1152=new Plyr('.un1152 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1152.volume=0.8;
un1152.on('enterfullscreen',function(){pop.hide('popup120');});un1152.on('exitfullscreen',function(){pop.show('popup120');});pop.addHook('popup120',null,function(){un1152.stop()});un1153=new Plyr('.un1153 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1153.volume=0.8;
un1153.on('enterfullscreen',function(){pop.hide('popup118');});un1153.on('exitfullscreen',function(){pop.show('popup118');});pop.addHook('popup118',null,function(){un1153.stop()});un1154=new Plyr('.un1154 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1154.volume=0.8;
un1154.on('enterfullscreen',function(){pop.hide('popup119');});un1154.on('exitfullscreen',function(){pop.show('popup119');});pop.addHook('popup119',null,function(){un1154.stop()});un1155=new Plyr('.un1155 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1155.volume=0.8;
un1155.on('enterfullscreen',function(){pop.hide('popup117');});un1155.on('exitfullscreen',function(){pop.show('popup117');});pop.addHook('popup117',null,function(){un1155.stop()});un1156=new Plyr('.un1156 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1156.volume=0.8;
un1156.on('enterfullscreen',function(){pop.hide('popup116');});un1156.on('exitfullscreen',function(){pop.show('popup116');});pop.addHook('popup116',null,function(){un1156.stop()});un1157=new Plyr('.un1157 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1157.volume=0.8;
un1157.on('enterfullscreen',function(){pop.hide('popup115');});un1157.on('exitfullscreen',function(){pop.show('popup115');});pop.addHook('popup115',null,function(){un1157.stop()});un1158=new Plyr('.un1158 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1158.volume=0.8;
un1158.on('enterfullscreen',function(){pop.hide('popup113');});un1158.on('exitfullscreen',function(){pop.show('popup113');});pop.addHook('popup113',null,function(){un1158.stop()});un1159=new Plyr('.un1159 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1159.volume=0.8;
un1159.on('enterfullscreen',function(){pop.hide('popup114');});un1159.on('exitfullscreen',function(){pop.show('popup114');});pop.addHook('popup114',null,function(){un1159.stop()});un1160=new Plyr('.un1160 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1160.volume=0.8;
un1160.on('enterfullscreen',function(){pop.hide('popup112');});un1160.on('exitfullscreen',function(){pop.show('popup112');});pop.addHook('popup112',null,function(){un1160.stop()});un1161=new Plyr('.un1161 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1161.volume=0.8;
un1161.on('enterfullscreen',function(){pop.hide('popup111');});un1161.on('exitfullscreen',function(){pop.show('popup111');});pop.addHook('popup111',null,function(){un1161.stop()});un1162=new Plyr('.un1162 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1162.volume=0.8;
un1162.on('enterfullscreen',function(){pop.hide('popup122');});un1162.on('exitfullscreen',function(){pop.show('popup122');});pop.addHook('popup122',null,function(){un1162.stop()});un1163=new Plyr('.un1163 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1163.volume=0.8;
un1163.on('enterfullscreen',function(){pop.hide('popup109');});un1163.on('exitfullscreen',function(){pop.show('popup109');});pop.addHook('popup109',null,function(){un1163.stop()});un1164=new Plyr('.un1164 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1164.volume=0.8;
un1164.on('enterfullscreen',function(){pop.hide('popup110');});un1164.on('exitfullscreen',function(){pop.show('popup110');});pop.addHook('popup110',null,function(){un1164.stop()});un1165=new Plyr('.un1165 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1165.volume=0.8;
un1165.on('enterfullscreen',function(){pop.hide('popup108');});un1165.on('exitfullscreen',function(){pop.show('popup108');});pop.addHook('popup108',null,function(){un1165.stop()});un1166=new Plyr('.un1166 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1166.volume=0.8;
un1166.on('enterfullscreen',function(){pop.hide('popup107');});un1166.on('exitfullscreen',function(){pop.show('popup107');});pop.addHook('popup107',null,function(){un1166.stop()});un1167=new Plyr('.un1167 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1167.volume=0.8;
un1167.on('enterfullscreen',function(){pop.hide('popup106');});un1167.on('exitfullscreen',function(){pop.show('popup106');});pop.addHook('popup106',null,function(){un1167.stop()});un1168=new Plyr('.un1168 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1168.volume=0.8;
un1168.on('enterfullscreen',function(){pop.hide('popup104');});un1168.on('exitfullscreen',function(){pop.show('popup104');});pop.addHook('popup104',null,function(){un1168.stop()});un1169=new Plyr('.un1169 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1169.volume=0.8;
un1169.on('enterfullscreen',function(){pop.hide('popup105');});un1169.on('exitfullscreen',function(){pop.show('popup105');});pop.addHook('popup105',null,function(){un1169.stop()});un1170=new Plyr('.un1170 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1170.volume=0.8;
un1170.on('enterfullscreen',function(){pop.hide('popup103');});un1170.on('exitfullscreen',function(){pop.show('popup103');});pop.addHook('popup103',null,function(){un1170.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un1296 source');ldsrcset('.un1297 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}