(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un1477');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-42.php':'images/transparentks-284-79.php'):'images/transparentks-142-122.php');
var a='data-src';var e=document.querySelector('.un1478');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-42.php':'images/k-stransparent-424-85.php');
var e=document.querySelector('.un1474');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-40.php':'images/transparentks-284-78.php'):'images/transparentks-142-120.php');
var e=document.querySelector('.un1475');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-42.php':'images/k-stransparent-424-85.php');
var e=document.querySelector('.un1476');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-20.php':'images/csi-logo-272-40.php'):'images/csi-logo-136-81.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un1477');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-42.php':'images/transparentks-178-87.php'):'images/transparentks-89-87.php');
var a='data-src';var e=document.querySelector('.un1478');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-42.php':'images/k-stransparent-265-42.php');
var e=document.querySelector('.un1474');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-40.php':'images/transparentks-178-86.php'):'images/transparentks-89-86.php');
var e=document.querySelector('.un1475');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-42.php':'images/k-stransparent-265-42.php');
var e=document.querySelector('.un1476');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-20.php':'images/csi-logo-170-40.php'):'images/csi-logo-85-40.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un1477');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-20.php':'images/transparentks-142-121.php'):'images/transparentks-71-42.php');
var a='data-src';var e=document.querySelector('.un1478');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-20.php':'images/k-stransparent-424-84.php'):'images/k-stransparent-212-42.php');
var e=document.querySelector('.un1474');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-20.php':'images/transparentks-138-36.php'):'images/transparentks-69-36.php');
var e=document.querySelector('.un1475');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-20.php':'images/k-stransparent-424-84.php'):'images/k-stransparent-212-42.php');
var e=document.querySelector('.un1476');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-20.php':'images/csi-logo-136-80.php'):'images/csi-logo-68-40.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un1477');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-20.php':'images/transparentks-114-46.php'):'images/transparentks-57-46.php');
var a='data-src';var e=document.querySelector('.un1478');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-20.php':'images/k-stransparent-340-40.php'):'images/k-stransparent-170-40.php');
var e=document.querySelector('.un1474');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-20.php':'images/transparentks-110-36.php'):'images/transparentks-55-36.php');
var e=document.querySelector('.un1475');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-20.php':'images/k-stransparent-340-40.php'):'images/k-stransparent-170-40.php');
var e=document.querySelector('.un1476');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-20.php':'images/csi-logo-108-40.php'):'images/csi-logo-54-40.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un1477');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-20.php':'images/transparentks-306-42.php'):'images/transparentks-153-42.php');
var a='data-src';var e=document.querySelector('.un1478');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-20.php':'images/k-stransparent-330-42.php'):'images/k-stransparent-165-42.php');
var e=document.querySelector('.un1474');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-20.php':'images/transparentks-192-42.php'):'images/transparentks-96-42.php');
var e=document.querySelector('.un1475');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-20.php':'images/k-stransparent-392-34.php'):'images/k-stransparent-196-34.php');
var e=document.querySelector('.un1476');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-20.php':'images/csi-logo-174-34.php'):'images/csi-logo-87-34.php');}else{var a='data-src';var e=document.querySelector('.un1477');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-68.php':'images/transparentks-204-42.php'):'images/transparentks-102-42.php');
var a='data-src';var e=document.querySelector('.un1478');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-68.php':'images/k-stransparent-220-42.php'):'images/k-stransparent-110-42.php');
var e=document.querySelector('.un1474');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-68.php':'images/transparentks-128-42.php'):'images/transparentks-64-42.php');
var e=document.querySelector('.un1475');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-20.php':'images/k-stransparent-262-34.php'):'images/k-stransparent-131-34.php');
var e=document.querySelector('.un1476');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-60.php':'images/csi-logo-116-34.php'):'images/csi-logo-58-34.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un1479=new Plyr('.un1479 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1479.volume=0.8;
un1479.on('enterfullscreen',function(){pop.hide('popup164');});un1479.on('exitfullscreen',function(){pop.show('popup164');});pop.addHook('popup164',null,function(){un1479.stop()});un1480=new Plyr('.un1480 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1480.volume=0.8;
un1480.on('enterfullscreen',function(){pop.hide('popup163');});un1480.on('exitfullscreen',function(){pop.show('popup163');});pop.addHook('popup163',null,function(){un1480.stop()});un1481=new Plyr('.un1481 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1481.volume=0.8;
un1481.on('enterfullscreen',function(){pop.hide('popup162');});un1481.on('exitfullscreen',function(){pop.show('popup162');});pop.addHook('popup162',null,function(){un1481.stop()});un1482=new Plyr('.un1482 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1482.volume=0.8;
un1482.on('enterfullscreen',function(){pop.hide('popup165');});un1482.on('exitfullscreen',function(){pop.show('popup165');});pop.addHook('popup165',null,function(){un1482.stop()});un1483=new Plyr('.un1483 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1483.volume=0.8;
un1483.on('enterfullscreen',function(){pop.hide('popup161');});un1483.on('exitfullscreen',function(){pop.show('popup161');});pop.addHook('popup161',null,function(){un1483.stop()});un1484=new Plyr('.un1484 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1484.volume=0.8;
un1484.on('enterfullscreen',function(){pop.hide('popup160');});un1484.on('exitfullscreen',function(){pop.show('popup160');});pop.addHook('popup160',null,function(){un1484.stop()});un1485=new Plyr('.un1485 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1485.volume=0.8;
un1485.on('enterfullscreen',function(){pop.hide('popup159');});un1485.on('exitfullscreen',function(){pop.show('popup159');});pop.addHook('popup159',null,function(){un1485.stop()});un1486=new Plyr('.un1486 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1486.volume=0.8;
un1486.on('enterfullscreen',function(){pop.hide('popup158');});un1486.on('exitfullscreen',function(){pop.show('popup158');});pop.addHook('popup158',null,function(){un1486.stop()});un1487=new Plyr('.un1487 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1487.volume=0.8;
un1487.on('enterfullscreen',function(){pop.hide('popup157');});un1487.on('exitfullscreen',function(){pop.show('popup157');});pop.addHook('popup157',null,function(){un1487.stop()});un1488=new Plyr('.un1488 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1488.volume=0.8;
un1488.on('enterfullscreen',function(){pop.hide('popup156');});un1488.on('exitfullscreen',function(){pop.show('popup156');});pop.addHook('popup156',null,function(){un1488.stop()});un1489=new Plyr('.un1489 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1489.volume=0.8;
un1489.on('enterfullscreen',function(){pop.hide('popup155');});un1489.on('exitfullscreen',function(){pop.show('popup155');});pop.addHook('popup155',null,function(){un1489.stop()});un1490=new Plyr('.un1490 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1490.volume=0.8;
un1490.on('enterfullscreen',function(){pop.hide('popup154');});un1490.on('exitfullscreen',function(){pop.show('popup154');});pop.addHook('popup154',null,function(){un1490.stop()});un1491=new Plyr('.un1491 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1491.volume=0.8;
un1491.on('enterfullscreen',function(){pop.hide('popup153');});un1491.on('exitfullscreen',function(){pop.show('popup153');});pop.addHook('popup153',null,function(){un1491.stop()});un1492=new Plyr('.un1492 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1492.volume=0.8;
un1492.on('enterfullscreen',function(){pop.hide('popup152');});un1492.on('exitfullscreen',function(){pop.show('popup152');});pop.addHook('popup152',null,function(){un1492.stop()});un1493=new Plyr('.un1493 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1493.volume=0.8;
un1493.on('enterfullscreen',function(){pop.hide('popup151');});un1493.on('exitfullscreen',function(){pop.show('popup151');});pop.addHook('popup151',null,function(){un1493.stop()});un1494=new Plyr('.un1494 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1494.volume=0.8;
un1494.on('enterfullscreen',function(){pop.hide('popup150');});un1494.on('exitfullscreen',function(){pop.show('popup150');});pop.addHook('popup150',null,function(){un1494.stop()});un1495=new Plyr('.un1495 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1495.volume=0.8;
un1495.on('enterfullscreen',function(){pop.hide('popup149');});un1495.on('exitfullscreen',function(){pop.show('popup149');});pop.addHook('popup149',null,function(){un1495.stop()});un1496=new Plyr('.un1496 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1496.volume=0.8;
un1496.on('enterfullscreen',function(){pop.hide('popup148');});un1496.on('exitfullscreen',function(){pop.show('popup148');});pop.addHook('popup148',null,function(){un1496.stop()});un1497=new Plyr('.un1497 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1497.volume=0.8;
un1497.on('enterfullscreen',function(){pop.hide('popup166');});un1497.on('exitfullscreen',function(){pop.show('popup166');});pop.addHook('popup166',null,function(){un1497.stop()});un1498=new Plyr('.un1498 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un1498.volume=0.8;
un1498.on('enterfullscreen',function(){pop.hide('popup147');});un1498.on('exitfullscreen',function(){pop.show('popup147');});pop.addHook('popup147',null,function(){un1498.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un1624 source');ldsrcset('.un1625 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}