(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un771');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-22.php':'images/transparentks-284-71.php'):'images/transparentks-142-110.php');
var a='data-src';var e=document.querySelector('.un772');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-38.php':'images/k-stransparent-424-77.php');
var e=document.querySelector('.un768');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-20.php':'images/transparentks-284-70.php'):'images/transparentks-142-108.php');
var e=document.querySelector('.un769');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-38.php':'images/k-stransparent-424-77.php');
var e=document.querySelector('.un770');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-10.php':'images/csi-logo-272-36.php'):'images/csi-logo-136-73.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un771');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-22.php':'images/transparentks-178-79.php'):'images/transparentks-89-79.php');
var a='data-src';var e=document.querySelector('.un772');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-38.php':'images/k-stransparent-265-38.php');
var e=document.querySelector('.un768');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-20.php':'images/transparentks-178-78.php'):'images/transparentks-89-78.php');
var e=document.querySelector('.un769');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-38.php':'images/k-stransparent-265-38.php');
var e=document.querySelector('.un770');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-10.php':'images/csi-logo-170-36.php'):'images/csi-logo-85-36.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un771');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-10.php':'images/transparentks-142-109.php'):'images/transparentks-71-38.php');
var a='data-src';var e=document.querySelector('.un772');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-10.php':'images/k-stransparent-424-76.php'):'images/k-stransparent-212-38.php');
var e=document.querySelector('.un768');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-10.php':'images/transparentks-138-32.php'):'images/transparentks-69-32.php');
var e=document.querySelector('.un769');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-10.php':'images/k-stransparent-424-76.php'):'images/k-stransparent-212-38.php');
var e=document.querySelector('.un770');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-10.php':'images/csi-logo-136-72.php'):'images/csi-logo-68-36.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un771');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-10.php':'images/transparentks-114-42.php'):'images/transparentks-57-42.php');
var a='data-src';var e=document.querySelector('.un772');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-10.php':'images/k-stransparent-340-36.php'):'images/k-stransparent-170-36.php');
var e=document.querySelector('.un768');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-10.php':'images/transparentks-110-32.php'):'images/transparentks-55-32.php');
var e=document.querySelector('.un769');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-10.php':'images/k-stransparent-340-36.php'):'images/k-stransparent-170-36.php');
var e=document.querySelector('.un770');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-10.php':'images/csi-logo-108-36.php'):'images/csi-logo-54-36.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un771');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-10.php':'images/transparentks-306-38.php'):'images/transparentks-153-38.php');
var a='data-src';var e=document.querySelector('.un772');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-10.php':'images/k-stransparent-330-38.php'):'images/k-stransparent-165-38.php');
var e=document.querySelector('.un768');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-10.php':'images/transparentks-192-38.php'):'images/transparentks-96-38.php');
var e=document.querySelector('.un769');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-10.php':'images/k-stransparent-392-30.php'):'images/k-stransparent-196-30.php');
var e=document.querySelector('.un770');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-10.php':'images/csi-logo-174-30.php'):'images/csi-logo-87-30.php');}else{var a='data-src';var e=document.querySelector('.un771');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-54.php':'images/transparentks-204-38.php'):'images/transparentks-102-38.php');
var a='data-src';var e=document.querySelector('.un772');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-54.php':'images/k-stransparent-220-38.php'):'images/k-stransparent-110-38.php');
var e=document.querySelector('.un768');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-54.php':'images/transparentks-128-38.php'):'images/transparentks-64-38.php');
var e=document.querySelector('.un769');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-10.php':'images/k-stransparent-262-30.php'):'images/k-stransparent-131-30.php');
var e=document.querySelector('.un770');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-46.php':'images/csi-logo-116-30.php'):'images/csi-logo-58-30.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un773=new Plyr('.un773 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un773.volume=0.8;
un773.on('enterfullscreen',function(){pop.hide('popup65');});un773.on('exitfullscreen',function(){pop.show('popup65');});pop.addHook('popup65',null,function(){un773.stop()});un774=new Plyr('.un774 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un774.volume=0.8;
un774.on('enterfullscreen',function(){pop.hide('popup66');});un774.on('exitfullscreen',function(){pop.show('popup66');});pop.addHook('popup66',null,function(){un774.stop()});un775=new Plyr('.un775 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un775.volume=0.8;
un775.on('enterfullscreen',function(){pop.hide('popup64');});un775.on('exitfullscreen',function(){pop.show('popup64');});pop.addHook('popup64',null,function(){un775.stop()});un776=new Plyr('.un776 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un776.volume=0.8;
un776.on('enterfullscreen',function(){pop.hide('popup63');});un776.on('exitfullscreen',function(){pop.show('popup63');});pop.addHook('popup63',null,function(){un776.stop()});un777=new Plyr('.un777 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un777.volume=0.8;
un777.on('enterfullscreen',function(){pop.hide('popup62');});un777.on('exitfullscreen',function(){pop.show('popup62');});pop.addHook('popup62',null,function(){un777.stop()});un778=new Plyr('.un778 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un778.volume=0.8;
un778.on('enterfullscreen',function(){pop.hide('popup61');});un778.on('exitfullscreen',function(){pop.show('popup61');});pop.addHook('popup61',null,function(){un778.stop()});un779=new Plyr('.un779 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un779.volume=0.8;
un779.on('enterfullscreen',function(){pop.hide('popup60');});un779.on('exitfullscreen',function(){pop.show('popup60');});pop.addHook('popup60',null,function(){un779.stop()});un780=new Plyr('.un780 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un780.volume=0.8;
un780.on('enterfullscreen',function(){pop.hide('popup58');});un780.on('exitfullscreen',function(){pop.show('popup58');});pop.addHook('popup58',null,function(){un780.stop()});un781=new Plyr('.un781 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un781.volume=0.8;
un781.on('enterfullscreen',function(){pop.hide('popup57');});un781.on('exitfullscreen',function(){pop.show('popup57');});pop.addHook('popup57',null,function(){un781.stop()});un782=new Plyr('.un782 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un782.volume=0.8;
un782.on('enterfullscreen',function(){pop.hide('popup56');});un782.on('exitfullscreen',function(){pop.show('popup56');});pop.addHook('popup56',null,function(){un782.stop()});un783=new Plyr('.un783 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un783.volume=0.8;
un783.on('enterfullscreen',function(){pop.hide('popup67');});un783.on('exitfullscreen',function(){pop.show('popup67');});pop.addHook('popup67',null,function(){un783.stop()});un784=new Plyr('.un784 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un784.volume=0.8;
un784.on('enterfullscreen',function(){pop.hide('popup59');});un784.on('exitfullscreen',function(){pop.show('popup59');});pop.addHook('popup59',null,function(){un784.stop()});var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un870 source');ldsrcset('.un871 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}