(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un67');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/teams-450.php':'images/teams-300-4.php'):'images/teams-150-4.php');
var a='data-src';var e=document.querySelector('.un69');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-216.php');
var a='data-src';var e=document.querySelector('.un70');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-216.php');
var a='data-src';var e=document.querySelector('.un71');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-216.php');
var a='data-src';var e=document.querySelector('.un72');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-260.php');
var a='data-src';var e=document.querySelector('.un73');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-190-10.php');
var a='data-src';var e=document.querySelector('.un74');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-190-10.php');
var a='data-src';var e=document.querySelector('.un75');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-190-10.php');
var a='data-src';var e=document.querySelector('.un76');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-190-10.php');
var a='data-src';var e=document.querySelector('.un77');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-190-10.php');
var a='data-src';var e=document.querySelector('.un78');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-190-10.php');
var a='data-src';var e=document.querySelector('.un79');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-190-10.php');
var a='data-src';var e=document.querySelector('.un80');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-190-10.php');
var a='data-src';var e=document.querySelector('.un81');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-190-10.php');
var a='data-src';var e=document.querySelector('.un82');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-190-10.php');
var a='data-src';var e=document.querySelector('.un83');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-190-10.php');
var a='data-src';var e=document.querySelector('.un84');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-190-10.php');
var a='data-src';var e=document.querySelector('.un85');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-190-10.php');
var a='data-src';var e=document.querySelector('.un86');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cetim_152-262.php');
var a='data-src';var e=document.querySelector('.un87');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-190.php');
var a='data-src';var e=document.querySelector('.un88');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426-6.php':'images/transparentks-284-48.php'):'images/transparentks-142-76.php');
var a='data-src';var e=document.querySelector('.un89');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848-26.php':'images/k-stransparent-424-54.php');
var e=document.querySelector('.un63');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-4.php':'images/transparentks-284-46.php'):'images/transparentks-142-72.php');
var e=document.querySelector('.un64');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-26.php':'images/k-stransparent-424-54.php');
var e=document.querySelector('.un65');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-408-2.php':'images/csi-logo-272-24.php'):'images/csi-logo-136-50.php');
var e=document.querySelector('.un66');e.setAttribute('src',(dpi>1)?'images/program-3312.php':'images/program-1656-6.php');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un67');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/teams-282.php':'images/teams-188-4.php'):'images/teams-94-4.php');
var a='data-src';var e=document.querySelector('.un69');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-135.php');
var a='data-src';var e=document.querySelector('.un70');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-135.php');
var a='data-src';var e=document.querySelector('.un71');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-132.php');
var a='data-src';var e=document.querySelector('.un72');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-146.php');
var a='data-src';var e=document.querySelector('.un73');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-119-4.php');
var a='data-src';var e=document.querySelector('.un74');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-119-4.php');
var a='data-src';var e=document.querySelector('.un75');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-119-4.php');
var a='data-src';var e=document.querySelector('.un76');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-119-4.php');
var a='data-src';var e=document.querySelector('.un77');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-119-4.php');
var a='data-src';var e=document.querySelector('.un78');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-119-4.php');
var a='data-src';var e=document.querySelector('.un79');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-119-4.php');
var a='data-src';var e=document.querySelector('.un80');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-119-4.php');
var a='data-src';var e=document.querySelector('.un81');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-119-4.php');
var a='data-src';var e=document.querySelector('.un82');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-119-4.php');
var a='data-src';var e=document.querySelector('.un83');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-119-4.php');
var a='data-src';var e=document.querySelector('.un84');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-119-4.php');
var a='data-src';var e=document.querySelector('.un85');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-119-4.php');
var a='data-src';var e=document.querySelector('.un86');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cetim_152-152.php');
var a='data-src';var e=document.querySelector('.un87');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-119.php');
var a='data-src';var e=document.querySelector('.un88');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-267-6.php':'images/transparentks-178-56.php'):'images/transparentks-89-56.php');
var a='data-src';var e=document.querySelector('.un89');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530-26.php':'images/k-stransparent-265-26.php');
var e=document.querySelector('.un63');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-4.php':'images/transparentks-178-54.php'):'images/transparentks-89-54.php');
var e=document.querySelector('.un64');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-26.php':'images/k-stransparent-265-26.php');
var e=document.querySelector('.un65');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-255-2.php':'images/csi-logo-170-24.php'):'images/csi-logo-85-24.php');
var e=document.querySelector('.un66');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/program-3105.php':'images/program-2070-3.php'):'images/program-1035-3.php');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un67');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/teams-231.php':'images/teams-154-4.php'):'images/teams-77-4.php');
var a='data-src';var e=document.querySelector('.un69');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/enise-216-2.php':'images/enise-108.php');
var a='data-src';var e=document.querySelector('.un70');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ensam-216-2.php':'images/ensam-108.php');
var a='data-src';var e=document.querySelector('.un71');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ltds-216-2.php':'images/ltds-108.php');
var a='data-src';var e=document.querySelector('.un72');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/mrx_rays-228.php':'images/mrx_rays-114.php');
var a='data-src';var e=document.querySelector('.un73');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/brukeralicona-190-8.php':'images/brukeralicona-95-4.php');
var a='data-src';var e=document.querySelector('.un74');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/clubusinageinnovation-190-8.php':'images/clubusinageinnovation-95-4.php');
var a='data-src';var e=document.querySelector('.un75');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ingelyse-190-8.php':'images/ingelyse-95-4.php');
var a='data-src';var e=document.querySelector('.un76');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fondation_enise-190-8.php':'images/fondation_enise-95-4.php');
var a='data-src';var e=document.querySelector('.un77');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/labex_manutech-190-8.php':'images/labex_manutech-95-4.php');
var a='data-src';var e=document.querySelector('.un78');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/tivoly-190-8.php':'images/tivoly-95-4.php');
var a='data-src';var e=document.querySelector('.un79');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digitalsurf-190-8.php':'images/digitalsurf-95-4.php');
var a='data-src';var e=document.querySelector('.un80');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fives-190-8.php':'images/fives-95-4.php');
var a='data-src';var e=document.querySelector('.un81');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/institut_carnot-190-8.php':'images/institut_carnot-95-4.php');
var a='data-src';var e=document.querySelector('.un82');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/laregionaura-190-8.php':'images/laregionaura-95-4.php');
var a='data-src';var e=document.querySelector('.un83');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cnrs-190-8.php':'images/cnrs-95-4.php');
var a='data-src';var e=document.querySelector('.un84');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/onlylyon-190-8.php':'images/onlylyon-95-4.php');
var a='data-src';var e=document.querySelector('.un85');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/centraleinnovation-190-8.php':'images/centraleinnovation-95-4.php');
var a='data-src';var e=document.querySelector('.un86');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cetim_152-226.php':'images/cetim_152-113.php');
var a='data-src';var e=document.querySelector('.un87');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-95.php');
var a='data-src';var e=document.querySelector('.un88');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213-2.php':'images/transparentks-142-74.php'):'images/transparentks-71-26.php');
var a='data-src';var e=document.querySelector('.un89');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636-2.php':'images/k-stransparent-424-52.php'):'images/k-stransparent-212-26.php');
var e=document.querySelector('.un63');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-207-2.php':'images/transparentks-138-20.php'):'images/transparentks-69-20.php');
var e=document.querySelector('.un64');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-2.php':'images/k-stransparent-424-52.php'):'images/k-stransparent-212-26.php');
var e=document.querySelector('.un65');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-204-2.php':'images/csi-logo-136-48.php'):'images/csi-logo-68-24.php');
var e=document.querySelector('.un66');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/program-2442-2.php':'images/program-1628-2.php'):'images/program-814-2.php');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un67');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/teams-186.php':'images/teams-124.php'):'images/teams-62.php');
var a='data-src';var e=document.querySelector('.un69');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/enise-174.php':'images/enise-87.php');
var a='data-src';var e=document.querySelector('.un70');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ensam-172.php':'images/ensam-86.php');
var a='data-src';var e=document.querySelector('.un71');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ltds-174.php':'images/ltds-87.php');
var a='data-src';var e=document.querySelector('.un72');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/mrx_rays-184-2.php':'images/mrx_rays-92-2.php');
var a='data-src';var e=document.querySelector('.un73');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/brukeralicona-152-4.php':'images/brukeralicona-76-4.php');
var a='data-src';var e=document.querySelector('.un74');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/clubusinageinnovation-152-6.php':'images/clubusinageinnovation-76-6.php');
var a='data-src';var e=document.querySelector('.un75');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ingelyse-152-6.php':'images/ingelyse-76-6.php');
var a='data-src';var e=document.querySelector('.un76');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fondation_enise-152-4.php':'images/fondation_enise-76-4.php');
var a='data-src';var e=document.querySelector('.un77');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/labex_manutech-152-4.php':'images/labex_manutech-76-4.php');
var a='data-src';var e=document.querySelector('.un78');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/tivoly-152-4.php':'images/tivoly-76-4.php');
var a='data-src';var e=document.querySelector('.un79');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digitalsurf-152-4.php':'images/digitalsurf-76-4.php');
var a='data-src';var e=document.querySelector('.un80');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fives-152-4.php':'images/fives-76-4.php');
var a='data-src';var e=document.querySelector('.un81');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/institut_carnot-152-4.php':'images/institut_carnot-76-4.php');
var a='data-src';var e=document.querySelector('.un82');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/laregionaura-152-4.php':'images/laregionaura-76-4.php');
var a='data-src';var e=document.querySelector('.un83');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cnrs-152-4.php':'images/cnrs-76-4.php');
var a='data-src';var e=document.querySelector('.un84');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/onlylyon-152-6.php':'images/onlylyon-76-6.php');
var a='data-src';var e=document.querySelector('.un85');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/centraleinnovation-152-6.php':'images/centraleinnovation-76-6.php');
var a='data-src';var e=document.querySelector('.un86');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cetim_152-180-2.php':'images/cetim_152-90-2.php');
var a='data-src';var e=document.querySelector('.un87');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/knowledge_skill_123-152-2.php':'images/knowledge_skill_123-76-2.php');
var a='data-src';var e=document.querySelector('.un88');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171-2.php':'images/transparentks-114-30.php'):'images/transparentks-57-30.php');
var a='data-src';var e=document.querySelector('.un89');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510-2.php':'images/k-stransparent-340-24.php'):'images/k-stransparent-170-24.php');
var e=document.querySelector('.un63');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-165-2.php':'images/transparentks-110-20.php'):'images/transparentks-55-20.php');
var e=document.querySelector('.un64');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-510-2.php':'images/k-stransparent-340-24.php'):'images/k-stransparent-170-24.php');
var e=document.querySelector('.un65');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-162-2.php':'images/csi-logo-108-24.php'):'images/csi-logo-54-24.php');
var e=document.querySelector('.un66');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/program-1953-2.php':'images/program-1302-2.php'):'images/program-651-2.php');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un67');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/teams-441.php':'images/teams-294-4.php'):'images/teams-147-4.php');
var a='data-src';var e=document.querySelector('.un69');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-242-4.php');
var a='data-src';var e=document.querySelector('.un70');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-237-4.php');
var a='data-src';var e=document.querySelector('.un71');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-236-4.php');
var a='data-src';var e=document.querySelector('.un72');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-307.php');
var a='data-src';var e=document.querySelector('.un73');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-240-4.php');
var a='data-src';var e=document.querySelector('.un74');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-240-4.php');
var a='data-src';var e=document.querySelector('.un75');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-243-4.php');
var a='data-src';var e=document.querySelector('.un76');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-244-4.php');
var a='data-src';var e=document.querySelector('.un77');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-244-4.php');
var a='data-src';var e=document.querySelector('.un78');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-232-4.php');
var a='data-src';var e=document.querySelector('.un79');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-236-4.php');
var a='data-src';var e=document.querySelector('.un80');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-242-4.php');
var a='data-src';var e=document.querySelector('.un81');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-230-4.php');
var a='data-src';var e=document.querySelector('.un82');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-236-4.php');
var a='data-src';var e=document.querySelector('.un83');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-232-4.php');
var a='data-src';var e=document.querySelector('.un84');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-231-4.php');
var a='data-src';var e=document.querySelector('.un85');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-238-4.php');
var a='data-src';var e=document.querySelector('.un86');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cetim_152-307.php');
var a='data-src';var e=document.querySelector('.un87');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-238.php');
var a='data-src';var e=document.querySelector('.un88');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459-2.php':'images/transparentks-306-26.php'):'images/transparentks-153-26.php');
var a='data-src';var e=document.querySelector('.un89');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495-2.php':'images/k-stransparent-330-26.php'):'images/k-stransparent-165-26.php');
var e=document.querySelector('.un63');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-2.php':'images/transparentks-192-26.php'):'images/transparentks-96-26.php');
var e=document.querySelector('.un64');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-588-2.php':'images/k-stransparent-392-18.php'):'images/k-stransparent-196-18.php');
var e=document.querySelector('.un65');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-261-2.php':'images/csi-logo-174-18.php'):'images/csi-logo-87-18.php');
var e=document.querySelector('.un66');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/program-1242-2.php':'images/program-828-10.php'):'images/program-414-3.php');}else{var a='data-src';var e=document.querySelector('.un67');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/teams-294-6.php':'images/teams-196-4.php'):'images/teams-98-4.php');
var a='data-src';var e=document.querySelector('.un69');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/enise-161-4.php');
var a='data-src';var e=document.querySelector('.un70');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ensam-158-4.php');
var a='data-src';var e=document.querySelector('.un71');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ltds-157-4.php');
var a='data-src';var e=document.querySelector('.un72');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/mrx_rays-205.php');
var a='data-src';var e=document.querySelector('.un73');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-160-4.php');
var a='data-src';var e=document.querySelector('.un74');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-160-4.php');
var a='data-src';var e=document.querySelector('.un75');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-162-4.php');
var a='data-src';var e=document.querySelector('.un76');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-163-4.php');
var a='data-src';var e=document.querySelector('.un77');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-163-4.php');
var a='data-src';var e=document.querySelector('.un78');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-155-4.php');
var a='data-src';var e=document.querySelector('.un79');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-157-4.php');
var a='data-src';var e=document.querySelector('.un80');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-161-4.php');
var a='data-src';var e=document.querySelector('.un81');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-154-4.php');
var a='data-src';var e=document.querySelector('.un82');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-157-4.php');
var a='data-src';var e=document.querySelector('.un83');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-155-4.php');
var a='data-src';var e=document.querySelector('.un84');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-154-4.php');
var a='data-src';var e=document.querySelector('.un85');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-158-4.php');
var a='data-src';var e=document.querySelector('.un86');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cetim_152-205.php');
var a='data-src';var e=document.querySelector('.un87');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-158.php');
var a='data-src';var e=document.querySelector('.un88');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-46.php':'images/transparentks-204-26.php'):'images/transparentks-102-26.php');
var a='data-src';var e=document.querySelector('.un89');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-46.php':'images/k-stransparent-220-26.php'):'images/k-stransparent-110-26.php');
var e=document.querySelector('.un63');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-46.php':'images/transparentks-128-26.php'):'images/transparentks-64-26.php');
var e=document.querySelector('.un64');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-393-2.php':'images/k-stransparent-262-18.php'):'images/k-stransparent-131-18.php');
var e=document.querySelector('.un65');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/csi-logo-174-38.php':'images/csi-logo-116-18.php'):'images/csi-logo-58-18.php');
var e=document.querySelector('.un66');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/program-828-8.php':'images/program-552-3.php'):'images/program-276-3.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
$('form').h5Validate();$('.un247').mouseenter(function() { $.loadImages('images/program-2812.php', function() { }) });
$('.un247').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un247-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/program-2812.php'; } } });
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un225 source');ldsrcset('.un226 source');ldsrcset('.un227 source');ldsrcset('.un228 source');ldsrcset('.un229 source');ldsrcset('.un230 source');ldsrcset('.un231 source');ldsrcset('.un232 source');ldsrcset('.un233 source');ldsrcset('.un234 source');ldsrcset('.un235 source');ldsrcset('.un236 source');ldsrcset('.un237 source');ldsrcset('.un238 source');ldsrcset('.un239 source');ldsrcset('.un240 source');ldsrcset('.un241 source');ldsrcset('.un242 source');ldsrcset('.un243 source');ldsrcset('.un244 source');ldsrcset('.un245 source');ldsrcset('.un246 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}