(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};ldv=function(t){var e=document.querySelector(t),r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.play()};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-190-1.jpg');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-190-1.jpg');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-190-1.jpg');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-190-1.jpg');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-190-1.jpg');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-190-1.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-190-1.jpg');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-190-1.jpg');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-190-1.jpg');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-190-1.jpg');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-190-1.jpg');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-190-1.jpg');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-190-1.jpg');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-190.jpg');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-426.png':'images/transparentks-284.png'):'images/transparentks-142-1.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-848.png':'images/k-stransparent-424-1.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426.png':'images/transparentks-284.png'):'images/transparentks-142-1.png');
var e=document.querySelector('.un4');e.setAttribute('src','images/enise-216.jpg');
var e=document.querySelector('.un5');e.setAttribute('src','images/ensam-216.jpg');
var e=document.querySelector('.un6');e.setAttribute('src','images/ltds-216.jpg');
var e=document.querySelector('.un7');e.setAttribute('src','images/mrx_rays-260.jpg');
var e=document.querySelector('.un21');e.setAttribute('src','images/cetim_152-262.jpg');}else if($(window).width()>=1200){var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-119.jpg');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-119.jpg');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-119.jpg');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-119.jpg');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-119.jpg');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-119.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-119.jpg');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-119.jpg');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-119.jpg');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-119.jpg');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-119.jpg');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-119.jpg');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-119.jpg');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-119.jpg');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-264.png':'images/transparentks-176.png'):'images/transparentks-88.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/k-stransparent-530.png':'images/k-stransparent-265.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267.png':'images/transparentks-178.png'):'images/transparentks-89.png');
var e=document.querySelector('.un4');e.setAttribute('src','images/enise-135.jpg');
var e=document.querySelector('.un5');e.setAttribute('src','images/ensam-135.jpg');
var e=document.querySelector('.un6');e.setAttribute('src','images/ltds-132.jpg');
var e=document.querySelector('.un7');e.setAttribute('src','images/mrx_rays-146.jpg');
var e=document.querySelector('.un21');e.setAttribute('src','images/cetim_152-152.jpg');}else if($(window).width()>=960){var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/brukeralicona-190.jpg':'images/brukeralicona-95.jpg');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/clubusinageinnovation-190.jpg':'images/clubusinageinnovation-95.jpg');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ingelyse-190.jpg':'images/ingelyse-95.jpg');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fondation_enise-190.jpg':'images/fondation_enise-95.jpg');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/labex_manutech-190.jpg':'images/labex_manutech-95.jpg');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/tivoly-190.jpg':'images/tivoly-95.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digitalsurf-190.jpg':'images/digitalsurf-95.jpg');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fives-190.jpg':'images/fives-95.jpg');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/institut_carnot-190.jpg':'images/institut_carnot-95.jpg');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/laregionaura-190.jpg':'images/laregionaura-95.jpg');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cnrs-190.jpg':'images/cnrs-95.jpg');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/onlylyon-190.jpg':'images/onlylyon-95.jpg');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/centraleinnovation-190.jpg':'images/centraleinnovation-95.jpg');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-95.jpg');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-213.png':'images/transparentks-142.png'):'images/transparentks-71.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-636.png':'images/k-stransparent-424.png'):'images/k-stransparent-212.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-213.png':'images/transparentks-142.png'):'images/transparentks-71.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/enise-216-1.jpg':'images/enise-108.jpg');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/ensam-216-1.jpg':'images/ensam-108.jpg');
var e=document.querySelector('.un6');e.setAttribute('src',(dpi>1)?'images/ltds-216-1.jpg':'images/ltds-108.jpg');
var e=document.querySelector('.un7');e.setAttribute('src',(dpi>1)?'images/mrx_rays-228.jpg':'images/mrx_rays-114.jpg');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'images/cetim_152-226.jpg':'images/cetim_152-113.jpg');}else if($(window).width()>=768){var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/brukeralicona-152.jpg':'images/brukeralicona-76.jpg');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/clubusinageinnovation-152-1.jpg':'images/clubusinageinnovation-76-1.jpg');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ingelyse-152-1.jpg':'images/ingelyse-76-1.jpg');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fondation_enise-152-1.jpg':'images/fondation_enise-76-1.jpg');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/labex_manutech-152-1.jpg':'images/labex_manutech-76-1.jpg');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/tivoly-152.jpg':'images/tivoly-76.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/digitalsurf-152.jpg':'images/digitalsurf-76.jpg');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/fives-152.jpg':'images/fives-76.jpg');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/institut_carnot-152.jpg':'images/institut_carnot-76.jpg');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/laregionaura-152.jpg':'images/laregionaura-76.jpg');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/cnrs-152.jpg':'images/cnrs-76.jpg');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/onlylyon-152.jpg':'images/onlylyon-76.jpg');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/centraleinnovation-152.jpg':'images/centraleinnovation-76.jpg');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/knowledge_skill_123-152.jpg':'images/knowledge_skill_123-76.jpg');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-171.png':'images/transparentks-114.png'):'images/transparentks-57.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-510.png':'images/k-stransparent-340.png'):'images/k-stransparent-170.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-171.png':'images/transparentks-114.png'):'images/transparentks-57.png');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?'images/enise-174.jpg':'images/enise-87.jpg');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/ensam-172.jpg':'images/ensam-86.jpg');
var e=document.querySelector('.un6');e.setAttribute('src',(dpi>1)?'images/ltds-174.jpg':'images/ltds-87.jpg');
var e=document.querySelector('.un7');e.setAttribute('src',(dpi>1)?'images/mrx_rays-184.jpg':'images/mrx_rays-92.jpg');
var e=document.querySelector('.un21');e.setAttribute('src',(dpi>1)?'images/cetim_152-180.jpg':'images/cetim_152-90.jpg');}else if($(window).width()>=480){var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-240.jpg');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-240.jpg');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-243.jpg');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-245.jpg');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-244-1.jpg');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-232.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-236.jpg');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-240.jpg');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-231.jpg');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-236.jpg');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-232.jpg');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-230.jpg');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-237.jpg');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-236.jpg');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-459.png':'images/transparentks-306.png'):'images/transparentks-153.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-495.png':'images/k-stransparent-330.png'):'images/k-stransparent-165.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288.png':'images/transparentks-192.png'):'images/transparentks-96.png');
var e=document.querySelector('.un4');e.setAttribute('src','images/enise-242.jpg');
var e=document.querySelector('.un5');e.setAttribute('src','images/ensam-237.jpg');
var e=document.querySelector('.un6');e.setAttribute('src','images/ltds-236.jpg');
var e=document.querySelector('.un7');e.setAttribute('src','images/mrx_rays-307.jpg');
var e=document.querySelector('.un21');e.setAttribute('src','images/cetim_152-307.jpg');}else{var a='data-src';var e=document.querySelector('.un8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/brukeralicona-160.jpg');
var a='data-src';var e=document.querySelector('.un9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/clubusinageinnovation-160.jpg');
var a='data-src';var e=document.querySelector('.un10');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/ingelyse-162.jpg');
var a='data-src';var e=document.querySelector('.un11');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fondation_enise-163.jpg');
var a='data-src';var e=document.querySelector('.un12');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/labex_manutech-163.jpg');
var a='data-src';var e=document.querySelector('.un13');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/tivoly-155.jpg');
var a='data-src';var e=document.querySelector('.un14');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/digitalsurf-157.jpg');
var a='data-src';var e=document.querySelector('.un15');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/fives-161.jpg');
var a='data-src';var e=document.querySelector('.un16');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/institut_carnot-154.jpg');
var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/laregionaura-157.jpg');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/cnrs-155.jpg');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/onlylyon-154.jpg');
var a='data-src';var e=document.querySelector('.un20');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/centraleinnovation-158.jpg');
var a='data-src';var e=document.querySelector('.un22');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/knowledge_skill_123-158.jpg');
var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/transparentks-306-2.png':'images/transparentks-204.png'):'images/transparentks-102.png');
var a='data-src';var e=document.querySelector('.un24');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/k-stransparent-330-2.png':'images/k-stransparent-220.png'):'images/k-stransparent-110.png');
var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-1.png':'images/transparentks-128.png'):'images/transparentks-64.png');
var e=document.querySelector('.un4');e.setAttribute('src','images/enise-161.jpg');
var e=document.querySelector('.un5');e.setAttribute('src','images/ensam-158.jpg');
var e=document.querySelector('.un6');e.setAttribute('src','images/ltds-157.jpg');
var e=document.querySelector('.un7');e.setAttribute('src','images/mrx_rays-205.jpg');
var e=document.querySelector('.un21');e.setAttribute('src','images/cetim_152-205.jpg');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
un2=new Plyr('.un2 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time','mute','volume','fullscreen'],storage:{enabled:false}});
un2.volume=0.8;
un2.on('enterfullscreen',function(){pop.hide('popup1');});un2.on('exitfullscreen',function(){pop.show('popup1');});pop.addHook('popup1',null,function(){un2.stop()});un3=new Plyr('.un3 video',{iconUrl:'css/plyr.svg',blankUrl: 'css/blank.mp4',controls:['play-large','play','progress','current-time',,'fullscreen'],storage:{enabled:false}});
un3.volume=0.0;
initMenu($('#m1')[0]);
initMenu($('#m2')[0]);
initMenu($('#m3')[0]);
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un145 source');ldsrcset('.un146 source');ldsrcset('.un147 source');ldsrcset('.un148 source');ldsrcset('.un149 source');ldsrcset('.un150 source');ldsrcset('.un151 source');ldsrcset('.un152 source');ldsrcset('.un153 source');ldsrcset('.un154 source');ldsrcset('.un155 source');ldsrcset('.un156 source');ldsrcset('.un157 source');ldsrcset('.un158 source');ldsrcset('.un159 source');ldsrcset('.un160 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}