(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-56.php':'images/transparentks-284-98.php'):'images/transparentks-142-152.php');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-747.php':'images/transparentks-498.php'):'images/transparentks-249.php');
var e=document.querySelector('.un3');e.setAttribute('src','images/cirpcsi2022-483.php');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-426-56.php':'images/transparentks-284-98.php'):'images/transparentks-142-152.php');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/k-stransparent-848-52.php':'images/k-stransparent-424-106.php');}else if($(window).width()>=1200){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-56.php':'images/transparentks-178-106.php'):'images/transparentks-89-106.php');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-492.php':'images/transparentks-328.php'):'images/transparentks-164.php');
var e=document.querySelector('.un3');e.setAttribute('src','images/cirpcsi2022-305.php');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-267-58.php':'images/transparentks-178-108.php'):'images/transparentks-89-108.php');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?'images/k-stransparent-530-52.php':'images/k-stransparent-265-52.php');}else if($(window).width()>=960){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-213-28.php':'images/transparentks-142-150.php'):'images/transparentks-71-52.php');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-423.php':'images/transparentks-282.php'):'images/transparentks-141.php');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/cirpcsi2022-454.php':'images/cirpcsi2022-227.php');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-213-28.php':'images/transparentks-142-150.php'):'images/transparentks-71-52.php');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-636-28.php':'images/k-stransparent-424-104.php'):'images/k-stransparent-212-52.php');}else if($(window).width()>=768){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-171-28.php':'images/transparentks-114-56.php'):'images/transparentks-57-56.php');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-339.php':'images/transparentks-226.php'):'images/transparentks-113.php');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/cirpcsi2022-364.php':'images/cirpcsi2022-182.php');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-171-30.php':'images/transparentks-114-58.php'):'images/transparentks-57-58.php');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-507.php':'images/k-stransparent-338-4.php'):'images/k-stransparent-169-4.php');}else if($(window).width()>=480){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-288-28.php':'images/transparentks-192-82.php'):'images/transparentks-96-52.php');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-687.php':'images/transparentks-458.php'):'images/transparentks-229.php');
var e=document.querySelector('.un3');e.setAttribute('src','images/cirpcsi2022-423.php');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-459-30.php':'images/transparentks-306-84.php'):'images/transparentks-153-54.php');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-495-28.php':'images/k-stransparent-330-82.php'):'images/k-stransparent-165-52.php');}else{var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-192-80.php':'images/transparentks-128-52.php'):'images/transparentks-64-52.php');
var e=document.querySelector('.un2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-459-28.php':'images/transparentks-306-80.php'):'images/transparentks-153-52.php');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/cirpcsi2022-564.php':'images/cirpcsi2022-282.php');
var e=document.querySelector('.un4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/transparentks-306-82.php':'images/transparentks-204-52.php'):'images/transparentks-102-52.php');
var e=document.querySelector('.un5');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/k-stransparent-330-80.php':'images/k-stransparent-220-52.php'):'images/k-stransparent-110-52.php');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
var cs=new ConsentBanner('cookies_bar.html',undefined,0);cs.start(1);if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});